import LocalizedStrings from 'react-localization'

const LANG_EN = 'en'
const LANG_HANS = 'zh-hans'
let strings = new LocalizedStrings({
    'en': {
        mu_title: 'Mabot Firmware Upgrader Tool',
        mu_module_driver: ' Driver Ball ',
        mu_module_waist: ' Rotating Joint ',
        mu_module_arm: ' Swinging Joint ',
        mu_module_color: ' Color Sensor ',
        mu_module_ir: ' Infrared Sensor ',
        mu_module_touch: ' Touch Sensor ',
        noPlatform: "There is no driver software for this platform",
        l1_title_tips: 'Please connect Mabot using USB cable as shown above',
        l1_no_react: "Connected, but still not responding",
        l1_version: "Client version  V1.0",
        tips: "Tips",
        yes: "OK",
        no: "Cancel",
        up: "Upgrade",
        curr: "Current",
        cantfind:"Unrecognized",
        installDriver: 'Do you want to install the driver? ',
        installDriverNotice: 'After installing the driver, you must restart the computer',
        l1_no_mc: "No  Control Ball detected , please try the following",
        l1_for_1: "Method 1: Check if the USB cable is connected correctly",
        l1_for_2: "Method 2: Try to re-plug the Control Ball, or change the computer USB interface",
        l1_for_31: "Method 3:",
        l1_for_32: " Click to install the driver",
        l1_for_4: "Method 4: Turn off other software, or unplug other serial devices on your computer",
        l1_for_51: "Method 5: Check if the Control Ball keeps flashing red, if it keeps flashing red",
        l1_for_52: " Click to upgrade the Control Ball",
        service:"Contact Us",
        zhaot:"Email:",

        l1_if_connect: "Please check if the USB cable is connected correctly",
        l1_if_isblock: "Is the Mabot Control Ball always flashing red?",
        l2_choose: "Choose the ball to upgrade",
        curr_mc: 'Current Control Ball  version:',
        vers: "Version:  ",
        is_later: ' It is the latest version. ',
        not_later: ' Not the latest version',
        progress: "Installation progress",
        to_home: "Back to the home page",
        firm: "firmware",
        l3_ifmc_conn: 'Please check if the Control Ball  is connected',
        l3_mc_up: "Control Ball firmware upgrade",
        l3_usb_must: "Please connect the Mabot using the USB cable as shown above",
        l3_mc_islater: 'The current Control Ball firmware is already the latest version and no upgrade is required. ',
        l4_may_fail: 'This upgrade may fail, and the software will automatically re-upgrade later',
        l4_not_shutdown: 'The software cannot be closed during the upgrade process. The module cannot be plugged or unplugged. Do not turn off the power. Do not disconnect from the Control Ball! ',
        l4_not_work: "The above operation will cause the  module to be unusable.",
        l4_is_uping_mc: 'Upgrading the Control Ball firmware',
        l5_mc_is_done: "The  Control Ball was upgraded successfully and returned after 5% seconds",
        l6_mc_click: 'Click the button on the Control Ball',
        l7_ball_up: 'Firmware upgrade',
        l7_no_conn_until: 'has not been detected 1% , please click here',
        l7_up_module: "Upgrade mode",
        l7_not_jump: "Cannot jump to page in upgrade mode",
        l7_only_one: "You can only connect one 1% ，please remove the extra Functional ball",
        l7_insert_is: "You insert is 1%, whether about this 1% upgrade",
        l7_not_find: "Can not detected 1%，please insert 1%",
        l7_firm_islater: "The firmware is already the latest version and no upgrade is required.",
        l7_then_upMc: "Please upgrade the Control Ball  after all the function balls have been upgraded.",
        l7_then_contact_service: "Click the [Upgrade] button to re-upgrade the function ball. If the function ball is still not recognized, please contact customer service.",
        l8_is_uping: "upgrading",
        l8_up_fail: "Upgrade failed, please contact customer service",
        l9_is_done: "Upgrade is successful, return after 5% seconds",
        l10_1_pull: "First step: Please pull out The ",
        l10_2_push: "Second step ：After clicking the Upgrade button, insert 1% immediately when the Control Ball flashes green",
        l10_down_done:"Download finished",
        l10_do_downing:"Upgrade failed and firmware is being downloaded again"

    },

    'zh-hans': {
        mu_title: 'Mabot固件升级工具',
        mu_module_driver: '驱动球',
        mu_module_waist: '水平关节球',
        mu_module_arm: '摇摆关节球',
        mu_module_color: '颜色球',
        mu_module_ir: '红外球',
        mu_module_touch: '触碰球',
        noPlatform: "没有适配该平台的驱动软件",
        l1_title_tips: '请按如上图使用USB线连接Mabot',
        l1_no_react: "已连接上，但仍没有反应",
        l1_version: "客户端版本号V1.0",
        tips: "提示",
        yes: '确定',
        no: "取消",
        up: "升级",
        curr: "当前",
        cantfind:"未识别",
        installDriver: '确定安装驱动？',
        installDriverNotice: '安装完驱动后，你必须重启电脑才能生效',
        l1_no_mc: "未监测到主控，请尝试以下操作",
        l1_for_1: "方式一：检测USB线是否连接正确",
        l1_for_2: "方式二：尝试重新插拔主控，或者换个电脑USB接口",
        l1_for_31: "方式三：",
        l1_for_32: "点击安装驱动",
        l1_for_4: "方式四：关掉其他软件，或者拔掉电脑其他串口设备",
        l1_for_51: "方法五：检查主控是否一直闪红灯，如果一直闪红灯，",
        l1_for_52: "点击升级主控",
        service:"联系我们",
        zhaot:"联系邮箱：",

        l1_if_connect: "请检查USB线是否连接正确",
        l1_if_isblock: "Mabot主控是否一直闪红灯?",
        l2_choose: "选择要升级的球",
        curr_mc: '当前主控版本：',
        vers: "版本：",
        is_later: '，是最新版本',
        not_later: '，不是最新版本',
        progress: "安装进度",
        to_home: "返回首页",
        firm: "固件",
        l3_ifmc_conn: '请检查主控是否已连接',
        l3_mc_up: "主控球固件升级",
        l3_usb_must: "请按如上图使用USB线连接Mabot",
        l3_mc_islater: '当前主控球固件已经是最新版本，无需升级。',
        l4_may_fail: '本次升级可能会失败,稍后软件会自动重新升级',
        l4_not_shutdown: '升级过程中不可关闭软件，不可插拔模块，不可关闭电源，不可与主控断开连接！',
        l4_not_work: "上述操作会导致模块无法使用。",
        l4_is_uping_mc: '正在升级主控球固件',
        l5_mc_is_done: "主控球升级成功，5%秒后返回",
        l6_mc_click: '点击主控上的按钮',
        l7_ball_up: '固件升级',
        l7_no_conn_until: '一直未检测到1%，请点击这里',
        l7_up_module: "升级模式",
        l7_only_one: "只能连接一个1%，请拔下多余的功能球",
        l7_insert_is: "您插入的是1%，是否对该1%进行升级",
        l7_not_jump: "升级模式中不可跳转页面",
        l7_not_find: "未检测到1%，请插入1%",
        l7_firm_islater: "固件已经是最新版本，无需升级。",
        l7_then_upMc: "请在所有功能球升级完成后，再升级主控球。",
        l7_then_contact_service: "点击【升级】按钮重新升级功能球，如果还是未识别到功能球请联系客服。",
        l8_is_uping: "正在升级",
        l8_up_fail: "升级失败，请联系客服",
        l9_is_done: "升级成功，5%秒后返回",
        l10_1_pull: "第一步：请先拔掉",
        l10_2_push: "第二步：点击【升级】按钮后,当主控球闪绿灯时立即插入1%",
        l10_down_done:"下载完毕",
        l10_do_downing:"升级失败，正在重新下载固件",

    }
})

strings.setLanguage(LANG_HANS)

export {
    strings as default,
    LANG_EN,
    LANG_HANS,
}
